alias scz="source ~/.zshrc"
alias zshe="vim ~/.zshrc"
alias clc="fc -ln -1 | awk '{$1=$1}1' | pbcopy"
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias nvime="nvim ~/.config/nvim"
alias pull="git pull --ff-only --prune"
alias gs="git status"
alias ytt="/usr/local/bin/ytt.py"
alias prm="gh pr merge -md"
alias gfp="git add . && git commit --amend --no-edit && gp -f"
alias gi="gemini"
alias cl="claude"
alias ls='eza --long --header --icons --git'
alias rgs="rg --color=always --line-number --smart-case --hidden --glob '!{.git,node_modules,venv,dist,build}'"
alias kill-panel="tmux kill-pane -t"
