alias sc="source ~/.zshrc"
alias zshe="vim ~/.zshrc"
alias clc="fc -ln -1 | awk '{$1=$1}1' | pbcopy"
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias nvime="nvim ~/.config/nvim"
alias pull="git pull --ff-only --prune"
alias gs="git status"
alias ytt="/usr/local/bin/ytt.py"
alias prm="gh pr merge -md"
alias gfp="git add . && git commit --amend --no-edit && gp -f"
alias gi="gemini"
alias cl="claude"
